services:
  backend:
    build: .
    container_name: rag-backend
    restart: always
    env_file:
      - .env
    environment:
      HF_HOME: /app/.cache/huggingface
      TOKENIZERS_PARALLELISM: "false"
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - hf_cache:/app/.cache/huggingface

volumes:
  hf_cache: